const TitlesActionTypes={
    FETCH_GENRE_MOVIES_START:'FETCH_GENRE_MOVIES_START',
    FETCH_GENRE_MOVIES_SUCCESS:'FETCH_GENRE_MOVIES_SUCCESS',
    FETCH_GENRE_MOVIES_FAILURE:'FETCH_GENRE_MOVIES_FAILURE',

    FETCH_FRANCHISES_START:'FETCH_FRANCHISES_START',
    FETCH_FRANCHISES_SUCCESS:'FETCH_FRANCHISES_SUCCESS',
    FETCH_FRANCHISES_FAILURE:'FETCH_FRANCHISES_FAILURE',

    FETCH_MOVIE_WITH_ID_START:'FETCH_MOVIE_WITH_ID_START',
    FETCH_MOVIE_WITH_ID_SUCCESS:'FETCH_MOVIE_WITH_ID_SUCCESS',
    FETCH_MOVIE_WITH_ID_FAILURE:'FETCH_MOVIE_WITH_ID_FAILURE',

    FETCH_WISHLIST_START:'FETCH_WISHLIST_START',
    FETCH_WISHLIST_SUCCESS:'FETCH_WISHLIST_SUCCESS',
    FETCH_WISHLIST_FAILURE:'FETCH_WISHLIST_FAILURE',

    FETCH_SEARCH_START:'FETCH_SEARCH_START',
    FETCH_SEARCH_SUCCESS:'FETCH_SEARCH_SUCCESS',
    FETCH_SEARCH_FAILURE:'FETCH_SEARCH_FAILURE',

    FETCH_SUGGESTIONS_START:'FETCH_SUGGESTIONS_START',
    FETCH_SUGGESTIONS_SUCCESS:'FETCH_SUGGESTIONS_SUCCESS',
    FETCH_SUGGESTIONS_FAILURE:'FETCH_SUGGESTIONS_SUCCESS',

    FETCH_TOP_MOVIES_START:'FETCH_TOP_MOVIES_START',
    FETCH_TOP_MOVIES_SUCCESS:'FETCH_TOP_MOVIES_SUCCESS',
    FETCH_TOP_MOVIES_FAILURE:'FETCH_TOP_MOVIES_FAILURE',

    FETCH_RECENTS_START:'FETCH_RECENTS_START',
    FETCH_RECENTS_SUCCESS:'FETCH_RECENTS_SUCCESS',
    FETCH_RECENTS_FAILURE:'FETCH_RECENTS_FAILURE',

    FETCH_RECENTLY_VIEWED_START:'FETCH_RECENTLY_VIEWED_START',
    FETCH_RECENTLY_VIEWED_SUCCESS:'FETCH_RECENTLY_VIEWED_SUCCESS',
    FETCH_RECENTLY_VIEWED_FAILURE:'FETCH_RECENTLY_VIEWED_FAILURE',

    FETCH_TOP_HITS_START:'FETCH_TOP_HITS_START',
    FETCH_TOP_HITS_SUCCESS:'FETCH_TOP_HITS_SUCCESS',
    FETCH_TOP_HITS_FAILURE:'FETCH_TOP_HITS_FAILURE',

    FETCH_MOVIES_BY_YEAR_START:'FETCH_MOVIES_BY_YEAR_START',
    FETCH_MOVIES_BY_YEAR_SUCCESS:'FETCH_MOVIES_BY_YEAR_SUCCESS',
    FETCH_MOVIES_BY_YEAR_FAILURE:'FETCH_MOVIES_BY_YEAR_FAILURE',

    FETCH_SORT_MOVIES_START: 'FETCH_SORT_MOVIES_START',
    FETCH_SORT_MOVIES_SUCCESS: 'FETCH_SORT_MOVIES_SUCCESS',
    FETCH_SORT_MOVIES_FAILURE: 'FETCH_SORT_MOVIES_FAILURE',

    FETCH_TITLE_SUGGESTIONS_START: 'FETCH_TITLE_SUGGESTIONS_START',
    FETCH_TITLE_SUGGESTIONS_SUCCESS: 'FETCH_TITLE_SUGGESTIONS_SUCCESS',
    FETCH_TITLE_SUGGESTIONS_FAILURE: 'FETCH_TITLE_SUGGESTIONS_FAILURE'
};

export default TitlesActionTypes;