export const UserActionTypes={
    SET_CURRENT_USER:'SET_CURRENT_USER',
    ADD_TO_WISHLIST:'ADD_TO_WISHLIST',
    REMOVE_FROM_WISHLIST:'REMOVE_FROM_WISHLIST',
    ADD_TO_RECENTLY_VIEWED:'ADD_TO_RECENTLY_VIEWED'
}